### ISSUE TITLE
The RAI response is missing data and has incorrect data

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#151]
The `RegisterAppInterface` response is missing data and has incorrect data: 
* `displayCapabilities` is missing
* `vrCapabilities` has value `TEXT` when the generic_hmi does not support VR. 
* `hmiCapabilities` has value true for all the capabilities when generic_hmi does not support any of them
* `sdlVersion` has value `{GIT_COMMIT}`
* `audioPassThruCapabilities` returns data even though generic_hmi does not support the `PerformAudioPassThru` RPC.

**Comment by JackLivio** [comment]
> displayCapabilities is missing

Fixed by #155 

> vrCapabilities has value TEXT when the generic_hmi does not support VR.

Generic HMI does not send this value. [It is included in cores default capabilities file. You will have to remove/ "configure" this yourself.](https://github.com/smartdevicelink/sdl_core/blob/master/src/appMain/hmi_capabilities.json#L806)

> hmiCapabilities has value true for all the capabilities when generic_hmi does not support any of them

Fixed by #155.

> sdlVersion has value {GIT_COMMIT}

There is no autofill of this field. It needs to be manually populated in [core's .ini file](https://github.com/smartdevicelink/sdl_core/blob/master/src/appMain/smartDeviceLink.ini#L32)

> audioPassThruCapabilities returns data even though generic_hmi does not support the PerformAudioPassThru RPC.

Unfortunately this field is mandatory in the HMI API. This will need to be changed in Core not the HMI.
