### ISSUE TITLE
[SDL 0240] WebEngine support for SDL JavaScript

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/generic_hmi#231]
Proposal: [WebEngine support for SDL JavaScript](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0240-sdl-js-pwa.md)

> This proposal is adding a new transport to the SDL JavaScript library to support (progressive) web apps to run on a WebEngine or a browser.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/767

Steering Committee Decision:

>The Steering Committee voted to accept this proposal with the following revisions:
- When formatting `locales` in the `manifest.json` file, use standard [(RFC 5646)](https://tools.ietf.org/html/rfc5646), and convert locale strings when necessary.
- Do not specify the location of the manifest's <script> tag placement within the proposal.
- All revisions included in this PR: https://github.com/smartdevicelink/sdl_evolution/pull/888/files
> The proposal .md file was updated to reflect these revisions on 12/19/19.

**Comment by LuxoftAKutsan** [comment]
Hello @theresalech 

We have several questions related to WebEngine implementation for GenericHMI. 

1. Should it integrate implementation to 0240-sdl-js-pwa.md implementation? Or generic_hmi can emulate it? 
2. Should generic_hmi implement OEMStore emulation?

**Comment by JackLivio** [comment]
@LuxoftAKutsan 

1. The goal should be to allow the generic hmi to implement the feature entirely and be as close to production ready as we can make it. The generic hmi implementation should be able to run apps created by the sdl javascript suite.

2. Yes, I believe this is an important piece to the proposal implementation.

3. I would say this is optional but in order to test this feature there will need to be some sort of test demo application? We would use the demo apps in our review of the feature but I cant promise that they will be distributed with the project.

Let me know if you have any questions, I am happy to help.

**Comment by TinaKleczka** [comment]
@theresalech The additional scope of work for Generic HMI not required for Ford.  We would like to propose asking the Steering Committee to vote on allowing Ford to donate this portion of development at a later time, included with a future contribution. We would like this to be considered due to the urgent need of the WebEngine Support implementation for a prioritized project within Ford Motor Company's 2020 Roadmap.

**Comment by joeygrover** [comment]
@TinaKleczka I believe Jack has already left some comments and change requests that he is working with the authors on. We are looking to have these addressed before merging and will continue to work with the authors so there is a common understanding for the expectations of the feature.

**Comment by theresalech** [comment]
Hi @TinaKleczka - Can you please advise when Ford would be able to contribute the Generic HMI implementation of this feature?  We would like to include that date in the Steering Committee meeting discussion, as it will help members to understand the impact of the delay.  It’s worth noting that the Generic HMI implementation is required for Manticore to support this feature, and it is our understanding that there are SDLC members whose SDL integrations are dependent on the Generic HMI.  Therefore, we do not consider a feature implementation complete until it’s been added to all impacted platforms.  During the Steering Committee discussion, it will be the Project Maintainer’s recommendation to hold off on releases until all impacted platforms have implemented the WebEngine support feature.

**Comment by TinaKleczka** [comment]
@theresalech Thank you, our current estimate of hours is 400.  I will review a date with the team.  At this time please understand the criticality of assuring this is implemented to meet a Ford project requirement.  Question:  Would another member of the consortium have the bandwidth to complete this requirement and/or the Project Maintainer?

**Comment by theresalech** [comment]
@TinaKleczka We can pose that question to the Steering Committee to see if other members are able to assist.  The Project Maintainer can scope the effort as well, and bring findings to the next Steering Committee meeting.

**Comment by TinaKleczka** [comment]
@theresalech Thank you. It would be very welcomed and appreciated.

**Comment by theresalech** [comment]
Proposal markdown file has been updated per the revisions included in accepted Evolution Proposal [SDL 0240 Revisions - WebEngine support for SDL JavaScript](smartdevicelink/sdl_evolution#923). These revisions change the `appID` parameter within `GetAppProperties` to `policyAppID` and add a minlength of `1` to the param. Please see the proposal markdown file for more details.

**Comment by theresalech** [comment]
Closed via #240
