### ISSUE TITLE
[SDL 0031] Mobile Projection

### ISSUE THREAD

**Issue by JackLivio** [smartdevicelink/generic_hmi#38]
Proposal: [Mobile Projection](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0031-mobile-projection.md)

> The aim of the Mobile Projection feature is to allow application developers to create custom application use experiences that are not limited by HMI templates. Mobile Projection applications will be able to stream a video feed to the system and allow users to interact with the application by touching the system's screen.

Review: smartdevicelink/sdl_evolution#97

SDLC Steering Committee Decision:

> All members of the Steering Committee agreed this proposal is a good idea and should be accepted.

**Comment by Pixelfahnder** [comment]
I guess the idea behind this is obiously to mimic a similar behaviour like Apple Carplay, Android Auto and basically also Mirrolink which basically is not the worst thing to do. But it also comes with a big downside: Inconsistency of UI on the car. The current system of restricting UI views helps to keep the driver focused on the street which should be the main goal. It definitly helps to prevent driver distraction if only a few use cases are taken into account and therefore the safety not only of the driver but also the passengers and pedestrians as well as other drivers may rise.

Opening up for custom user experiences may lead to confusion because APP developer a may have the same functionality under different buttons or menus or have other levels of sub menus than the standard or APP developer b. Therefore this APPs have to be tested for usabiity and driver distration parameters by either the consortium or the OEMs.

Also opening up too much may also break the OEMs own styling for the HMI and will lead to inconsistent user experience. The own styling and branding guidelines will be given up as well.

**Maybe it is best to ask the APP developers what is missing in the current templates and bring the missing pieces into the standard.**

**Comment by joeljfischer** [comment]
@Pixelfahnder Hi, I'd just like to note that this isn't the best place to have this kind of discussion. This issue has been placed here due to the SDLC (the governing body of SDL) has already decided to add this app type. If you'd like to get involved in these kinds of discussions before the decisions have been made, see the "in review" proposals at www.github.com/smartdevicelink/issues

With that said, perhaps I can allay some of your concerns by noting that this is primarily targeted at OEM apps because OEMs are willing to take on the driver distraction implications. Consumer apps are unlikely to be permitted to video stream instead of templates. At a recent workshop we discussed enhancements to current templates and you'll see those proposals hopefully soon.

**Comment by Pixelfahnder** [comment]
@joeljfischer thanks for clearifying the place for such discussions. Restricting this to OEM or OEM certified APPs makes sense. I guess therefore most of my concerns are taken care of. Also I guess I have to propose something to enhance this concept even further. Providing some OEM UI control graphics via SDL from the HU to the mobile APP would be cool to help certified APP developers to integrate the same APP into multiple OEM's HUs without disturbing their user experience by having an own looking UI. But maybe I have to write a proposal for this.

**Comment by JackLivio** [comment]
Fixed in release of Generic HMI  0.10.0 and SDL Core 7.1.0
